config/routes.rb
Rails.application.routes.draw do
  resources :events, only: [:new, :create, :show, :index] do
    post 'attend', on: :member
  end
  root 'events#index'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :show, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :invitations, foreign_key: :attending_event_id
  has_many :attendees, through: :invitations

  scope :upcoming, -> { where("event_date >= ?", Time.current)}
  scope :past, -> { where("event_date < ?", Time.current)}
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :attending_event, class_name: "Event"
  belongs_to :attendee, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, foreign_key: "creator_id", class_name: 'Event'
  has_many :invitations, foreign_key: :attendee_id
  has_many :attending_events, through: :invitations
  # def upcoming_events
  #   @upcoming_events = self.attending_events.where("event_date >= ?", Time.current)
  # end
  # def past_events
  #   @past_events = self.attending_events.where("event_date < ?", Time.current)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    unless session[:user_id] == nil
      @current_user =  User.find(session[:user_id])
    end
    @event = Event.new
  end

  def create
    unless session[:user_id] == nil
      @current_user =  User.find(session[:user_id])
    end
    @event = @current_user.created_events.build(event_params)
    if @event.save
      flash[:success] = "Event successfully created"
      redirect_to @event
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
    @event.attendees << @event.creator
  end

  def show
    unless session[:user_id] == nil
      @current_user =  User.find(session[:user_id])
    end
    @event = Event.find(params[:id])
    Event.upcoming.include?(@event) ? @upcoming = true : @upcoming = false
    @attendees = @event.attendees
  end

  def index
    @upcoming_events = Event.upcoming.order('event_date ASC')
    @past_events = Event.past.order('event_date DESC')
  end

  def attend
    unless session[:user_id] == nil
      @current_user =  User.find(session[:user_id])
    end
    @event = Event.find(params[:id])
    unless @event.attendees.include?(@current_user)
      @event.attendees << @current_user
      @event.save
    else
      flash[:error] = "Already attending this event"
    end
    redirect_back(fallback_location: root_path)
  end
  

  private
  
  def event_params
    params.require(:event).permit(:name,:description,:event_date)
  end
  
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: session_params[:username])
    session[:user_id] = user.id
    redirect_to root_path, notice: "Logged In"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged Out"
  end
  private
  def session_params
    params.require(:signin)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: root_path }
        session[:user_id] = @user.id
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @user = User.find(params[:id])
    @hosting_events = @user.created_events
    @attending_events = @user.attending_events
    @upcoming_events = @user.attending_events.upcoming
    @past_events = @user.attending_events.past
  end

private
  def user_params
    params.require(:user).permit(:username,:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= simple_form_for @event do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <%= f.input :name  %>
    <%= f.input :description %>
    <%= f.input :event_date %>



    <%= f.button :submit %>

<% end %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th colspan="3">Upcoming Events</th>
    </tr>
  </thead>

  <tbody>
    <% @upcoming_events.each do |event| %>
      <tr>
        <td class='event'><%= link_to event.name, event %></td>
        <td><%= event.description %></td>

        <td><%= event.event_date.strftime("%m/%d/%Y")%></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<table>
  <thead>
    <tr>
      <th colspan="3">Past Events</th>
    </tr>
  </thead>

  <tbody>
    <% @past_events.each do |event| %>
      <tr>
        <td class='event'><%= link_to event.name, event %></td>
        <td><%= event.description %></td>

        <td><%= event.event_date.strftime("%m/%d/%Y")%></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @event.name %>
<h3>Hosted by: <%= link_to @event.creator.username, @event.creator %></h3>
<h5><%= @event.description %></h5>
<h5><%= @event.event_date.strftime("%m/%d/%Y") if !@event.event_date.nil? %></h5>
<h3>Attendees:</h3>
<% @attendees.each do |attendee| %>
  <h6><%= link_to attendee.username, attendee %></h6>
<% end %>
<% if !@current_user.nil? && @upcoming%>
  <%= button_to 'Attend', attend_event_path(@event), method: :post %>
<% elsif !@upcoming %>
  <p>Sorry, can't attend because this event has passed</p>
<% else %>
  <p>Must login to mark as attending</p>
<% end %>
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:alert] %>
    <%= flash[:notice] %>
    <button><%= link_to "Home", root_path %></button>
  <% unless session[:user_id] == nil %>
    <% current_user =  User.find(session[:user_id])%>
    <button><%= link_to "Logout", session_path(current_user), method: :delete %></button>
    <h3>You are <%=link_to current_user.username, current_user %></h3>
  <% else %>
    <button><%= link_to "Log In", new_session_path %></button>
    <button><%= link_to 'Sign Up', new_user_path %></button>
  <%end%>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>
<%= simple_form_for @user do |f| %>
  <%= f.input :username %>
  <%= f.input :email %>
  <%= f.button :submit %>
<% end %>

app/views/users/show.html.erb
<h1>Currently viewing <%= @user.username %>'s profile</h1>
<h3><%= @user.username %>'s Hosted Events:</h3>
<% @hosting_events.each do |event| %>
  <div class='event'>
    <h4>Name: <%= link_to event.name, event %></h4>
    <p>Description: <%= event.description %></p>
  </div>
<% end %>
<h3><%= @user.username %> will be at:</h3>
<% @upcoming_events.each do |event| %>
  <div class='event'>
    <h4>Name: <%= link_to event.name, event %></h4>
    <p>Description: <%= event.description %></p>
  </div>
<% end %>

<h3><%= @user.username %> was at: </h3>
<% @past_events.each do |event| %>
  <div class='event'>
    <h4>Name: <%= link_to event.name, event %></h4>
    <p>Description: <%= event.description %></p>
  </div>
<% end %>